version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: authtemplate
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ROOT_USER: spokay
    ports:
      - '3306'
    expose:
      - '3306'
