spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.name=divrsitee
enable-csrf=${csrf:false}
logging.level.org.springframework.security=DEBUG
#security.basic.enabled=false

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

jwt.secret=FhhveaQ/g2XVevsvLmoODpvq/Mq+NTLnaPpp1x2Y20rAm3+Xz7+Z0HA95CRy2nvgr6JvMFhCOpIvGr31/VZSvJY/fGMvWBtktT1Mr6IsMP4=
jwt.expiration=604800000
jwt.header=Authorization
jwt.prefix=Bearer 